services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ny_taxi
    volumes:
      - "~/zoomkamp_study/ny_taxi_pgdata:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - ny-taxi
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - "8080:80"
    networks:
      - ny-taxi
networks:
  ny-taxi:

